<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.29.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.57.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spaceship _Server\Spaceship _Server.csproj" />
    <ProjectReference Include="..\SpaceBattle.Lib\SpaceBattle.Lib.csproj" />
  </ItemGroup>

</Project>
